name: Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ join(matrix.*, '/') }}
    runs-on: ${{ matrix.os }}
    continue-on-error: "${{ !startsWith(matrix.os, 'ubuntu-') }}"
    env:
      CC: ${{ matrix.cc }}

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        cc:
        - gcc
        - clang

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate build scripts
      run: ./autogen.sh

    - name: Configure
      run: ./configure

    - name: Build
      run: make V=0

    - name: Test
      run: make V=0 check

    - name: Distcheck
      run: make distcheck
